version: '1.0.{build}'
image: Previous Visual Studio 2019
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet restore sdk/AWSXRayRecorder.sln
  - cmd: dotnet build sdk/AWSXRayRecorder.sln
clone_depth: 1
test_script:
  - cmd : dotnet test sdk/test/UnitTests
deploy: off
notifications:
  - provider: Email
    to:
     - aws-xray-peryton@amazon.com 
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
